id = "flatbuffers"
name = "FlatBuffers"
version = "0.0.2"
schema_version = 1
authors = ["Stephen Panaro"]
description = "FlatBuffers support."
repository = "https://github.com/smpanaro/zed-flatbuffers"
languages = ["languages/flatbuffers"]

[grammars.flatbuffers]
repository = "https://github.com/smpanaro/tree-sitter-flatbuffers"
commit = "2a0d56ecea626baf17a1f8d349e980c04246f343"

[language_servers.flatbuffers-language-server]
name = "FlatBuffers LSP"
language = "FlatBuffers"
